language: node_js
dist: trusty
node_js:
  - 8
sudo: false
notifications:
  email: false
script:
  - node --version
  - yarn --version
  - yarn run test

after_success:
  - yarn add codecov
  - codecov

branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email: false
